spring:
  application:
    name: muselink
  servlet:
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/muselink
      username: root
      password: qwer1234
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp:
      client:
        name: spring-ai-mcp-client
        version: 1.0.0
        enabled: true
        request-timeout: 30s
        type: sync
        stdio:
          servers-configuration: classpath:mcp-servers.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8120
server:
  port: 8123
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bottle.muselink.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# log
logging:
  level:
    # 关闭 MyBatis 的 Mapper 接口日志（SQL 打印）
    com.bottle.muselink.mapper: OFF
    # 关闭 MyBatis Plus 的日志
    com.baomidou.mybatisplus: OFF
    # 关闭 MyBatis Core 的日志
    org.apache.ibatis: OFF

    org.springframework.ai: DEBUG
    org.springframework.ai.transformer.splitter: WARN
websearch:
  api-key: ${BAIDU_SEARCH_API_KEY}