version: '3.8'
services:
  pgvector-db:
    image: pgvector/pgvector:0.8.0-pg17
    restart:  always
    container_name: psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - /Users/dpy/pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data: